"use client";

// src/app/dev/social-templates/use-on-demand.ts
//
// One generated by default, the rest on demand — Hemanth's model, 2026-09-23.
//
// ── What a variant actually is, corrected after review ──
//
// The first version of this tracked readiness per AXIS: a set of tones, and
// separately a set of lengths. That is not what a generation produces. A
// generation produces ONE ARTEFACT, and an artefact is a (tone, length) PAIR.
// Modelling the axes separately meant the two could not agree about what had
// been paid for.
//
// The symptom was specific and was caught in review: `XThread` was keyed by
// tone, so changing tone remounted it and discarded the lengths already
// generated. Going FORWARD that looked right — a new tone genuinely has
// nothing generated at any length. Coming BACK it was wrong, because the
// artefact you paid for a moment ago was marked unpaid again and would be
// charged for twice.
//
// So readiness is a set of KEYS, and the caller decides what a key means.
// The thread's keys carry tone and length; the description's carry tone
// alone, because it has no second axis and a key that encoded one would
// invent a variant the user cannot ask for.
//
// ── The race guard ──
//
// Asking for a variant starts async work the user can interrupt by asking for
// another before it lands. The token is taken BEFORE the wait and checked
// AFTER it, so a superseded run drops its result rather than yanking the view
// to something nobody is waiting for any more.
//
// A REF, never state. State read inside that closure is the value from the
// render that began the run — exactly the stale value the guard exists to
// catch. §13 records the create route learning this the hard way.
//
// A dropped run also leaves its key OUT of `ready`: a generation that was
// abandoned produced nothing, and recording it would let the next click skip
// a call that never happened.

import { useCallback, useEffect, useRef, useState } from "react";

export interface OnDemand {
  /** Keys already generated. Revisiting one of these costs nothing. */
  ready: ReadonlySet<string>;
  /** The key being generated right now, if any. */
  generating: string | null;
  /**
   * Ask for a variant.
   *
   * `commit` applies the selection — it runs immediately when the key is
   * already generated, and after the wait when it is not. Passing it in
   * rather than returning a value is what lets one hook drive two
   * independent selectors over the same set of artefacts.
   */
  request: (key: string, commit: () => void) => void;
  /**
   * Abandon whatever is in flight.
   *
   * Needed because not every navigation goes through `request`. Switching
   * platform changes which artefact is on screen without asking for one, and
   * a run left running would commit a selection for the platform you just
   * left. Sharing the token is what makes that one mechanism rather than two
   * that have to agree.
   */
  cancel: () => void;
}

/**
 * @param initialKeys  what a run produces without being asked. More than one
 *                     because this specimen shows two platforms, and each
 *                     has its own default artefact.
 * @param delayMs      stands in for the model call. A specimen has no
 *                     backend, and a state that resolves instantly cannot be
 *                     looked at.
 */
export function useOnDemand(
  initialKeys: readonly string[],
  delayMs: number = 900,
): OnDemand {
  const [ready, setReady] = useState<ReadonlySet<string>>(
    () => new Set(initialKeys),
  );
  const [generating, setGenerating] = useState<string | null>(null);

  const runToken = useRef(0);
  const timer = useRef<number | null>(null);

  useEffect(() => {
    return () => {
      if (timer.current !== null) window.clearTimeout(timer.current);
    };
  }, []);

  const request = useCallback(
    (key: string, commit: () => void) => {
      // Bump first. This both claims the new run and invalidates any in
      // flight, so the two cases share one mechanism rather than one of them
      // depending on remembering to cancel.
      const token = ++runToken.current;

      if (ready.has(key)) {
        setGenerating(null);
        commit();
        return;
      }

      setGenerating(key);
      if (timer.current !== null) window.clearTimeout(timer.current);
      timer.current = window.setTimeout(() => {
        if (token !== runToken.current) return;
        setReady((prev) => new Set(prev).add(key));
        commit();
        setGenerating(null);
      }, delayMs);
    },
    [ready, delayMs],
  );

  const cancel = useCallback(() => {
    runToken.current += 1;
    if (timer.current !== null) window.clearTimeout(timer.current);
    setGenerating(null);
  }, []);

  return { ready, generating, request, cancel };
}
