"use client";

// src/app/dev/social-templates/use-on-demand.ts
//
// One generated by default, the rest on demand — Hemanth's model, 2026-09-23,
// and now the rule for every variant axis rather than just length.
//
// ── Why this is shared rather than written twice ──
//
// It was length only, inside the thread. Tone then moved to the same model,
// which made a second consumer, which is the bar this project sets for
// promoting a utility. Two copies of a race guard is two places for it to be
// subtly wrong.
//
// ── What it actually is ──
//
// A set of variants where exactly one exists at the start and the others cost
// a model call to obtain. The hook owns which one is showing, which ones have
// been paid for, and which one is being fetched right now.
//
// ── The race guard, which is the whole reason this is not four lines ──
//
// Asking for a variant starts async work the user can interrupt by asking for
// another before it lands. The token is taken BEFORE the wait and checked
// AFTER it, so a superseded run drops its result rather than yanking the view
// to something nobody is waiting for any more.
//
// A REF, never state. State read inside that closure is the value from the
// render that began the run — which is exactly the stale value the guard
// exists to catch. §13 records the create route learning this the hard way.

import { useCallback, useEffect, useRef, useState } from "react";

export interface OnDemand<T extends string> {
  /** The variant currently on screen. */
  value: T;
  /** Variants that have been generated and cost nothing to revisit. */
  ready: ReadonlySet<T>;
  /** The variant being generated right now, if any. */
  generating: T | null;
  /** Ask for a variant. Free if ready, a simulated model call if not. */
  request: (next: T) => void;
}

/**
 * @param initial  the variant a run produces without being asked
 * @param delayMs  stands in for the model call. A specimen has no backend,
 *                 and a state that resolves instantly cannot be looked at.
 */
export function useOnDemand<T extends string>(
  initial: T,
  delayMs: number = 900,
): OnDemand<T> {
  const [value, setValue] = useState<T>(initial);
  const [ready, setReady] = useState<ReadonlySet<T>>(() => new Set<T>([initial]));
  const [generating, setGenerating] = useState<T | null>(null);

  const runToken = useRef(0);
  const timer = useRef<number | null>(null);

  useEffect(() => {
    return () => {
      if (timer.current !== null) window.clearTimeout(timer.current);
    };
  }, []);

  const request = useCallback(
    (next: T) => {
      // Bump first. This both claims the new run and invalidates any in
      // flight, so the two cases share one mechanism rather than one of them
      // being handled by remembering to cancel.
      const token = ++runToken.current;

      if (ready.has(next)) {
        setGenerating(null);
        setValue(next);
        return;
      }

      setGenerating(next);
      if (timer.current !== null) window.clearTimeout(timer.current);
      timer.current = window.setTimeout(() => {
        if (token !== runToken.current) return;
        setReady((prev) => new Set(prev).add(next));
        setValue(next);
        setGenerating(null);
      }, delayMs);
    },
    [ready, delayMs],
  );

  return { value, ready, generating, request };
}
